LOGIN_SESSION_KEY = 'login'
AUTHENT_SESSION_KEY = 'authentification'

MAX_RECURSION_DEPTH = 10

TUTORIAL_FUNCTION_TITLE = "STEPS FOR THIS FUNCTION"
PARAMETERS_SOURCE_TITLE = "PARAMETER TO LAUNCH TREATMENT"
PARAMETERS_MODES_TITLE = "MODES FOR THIS FUNCTION"
# TODO : A UTILISER ET GENERALISER STRINGS

FILE_INPUT_KEY = 'file_of_words'
TEXT_INPUT_KEY = 'word_txt'
TERMINAL_MODE_KEY = 'term_mode'
NOTERM_MODES_KEY = 'noTerm_modes'

